### ISSUE TITLE
Support TypeDoc v0.16.11

### ISSUE THREAD

**Issue by jalextowle** [0xProject/ts-doc-gen#4]
## Description
This tool will crash with an error when using the latest version of TypeDoc, v0.16.11, when the TypeDoc configuration file is omitted. Since `@0x/ts-doc-gen` has a dependency of TypeDoc v^0.15.0, this can't necessarily be considered a bug; however, the latest releases of TypeDoc contain some improvements that would be worth supporting in `@0x/ts-doc-gen`.

## Expected Behavior
Generates TypeDoc v0.16.11 documentation.

## Actual Behavior
Crashes with the following error:

```
typedoc command failed:  { Error: Command failed: ./node_modules/.bin/typedoc --theme markdown --platform gitbook --ignoreCompilerErrors --excludePrivate --excludeProtected --excludeExternals --excludeNotExported --target ES5 --module commonjs --hideGenerator --out ../../docs/browser-bindings/browser src

    at ChildProcess.exithandler (child_process.js:299:12)
    at ChildProcess.emit (events.js:193:13)
    at maybeClose (internal/child_process.js:999:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:266:5)
  killed: false,
  code: 1,
  signal: null,
  cmd:
   './node_modules/.bin/typedoc --theme markdown --platform gitbook --ignoreCompilerErrors --excludePrivate --excludeProtected --excludeExternals --excludeNotExported --target ES5 --module commonjs --hideGenerator --out ../../docs/browser-bindings/browser src',
  stdout:
   'Error: Unknown option: --platform\nError: Unknown option: --platform\n',
  stderr: '' }
```

**Comment by jalextowle** [comment]
This should have been fixed by #5
